### ISSUE TITLE
approx_conv_multiplications @ lab02

### ISSUE THREAD

**Issue by magomagic** [the-full-stack/fsdl-text-recognizer-2022#76]
Hi ! I am reviewing the lab notebook and watching the course videos with great enjoyment.
I have a question regarding the function approx_conv_multiplications().
It is not clear to me why num_input_channels is used in the calculation. It seems to me this dimension is  already counted in  num_kernel_elements(multiplication of all 3 dimensions of the kernel).

I suggest changing :
mutliplications_per_kernel = num_spatial_applications * num_kernel_elements * num_input_channels
to:
 mutliplications_per_kernel = num_spatial_applications * num_kernel_elements

BR,
magomagic

**Comment by charlesfrye** [comment]
you're right! thanks for letting us know.
