### ISSUE TITLE
Versions of PIL and urllib3 are out of sync with Colab, requiring restart

### ISSUE THREAD

**Issue by charlesfrye** [the-full-stack/fsdl-text-recognizer-2022#78]
PIL version constraint just needs to be updated to `>=9.4,<9.5`

urllib3 is not currently constrained

**Comment by charlesfrye** [comment]
Thanks for the offer! I think I need to handle this one.

The process for testing is manual and under-documented -- this repo is meant to demo how to organize a DL _product_ codebase, not a DL _course_ codebase, so the back-of-house stuff isn't so clean.

**Comment by johntharian** [comment]
oh okay, cool

**Comment by charlesfrye** [comment]
this seems to be fixed -- the restart is only required in the testing notebook
