### ISSUE TITLE
torch and torchtext versions incompatible in Lab 06

### ISSUE THREAD

**Issue by triakshunn** [the-full-stack/fsdl-text-recognizer-2022#80]
In Lab06_data file, the current env gives the error 
![image](https://github.com/the-full-stack/fsdl-text-recognizer-2022/assets/35093460/f4fd0692-1eb8-4bd4-8f87-532ce7f60142)
the error happens because the current env has torch 2.0.1 and torchtext 0.16.0 which are incompatible. See [here](https://github.com/pytorch/text#installation)

Solution: Downgrading torchtext to 0.15.2 solves the issue.

**Comment by charlesfrye** [comment]
thanks for reporting! resolved in 547997b
