### ISSUE TITLE
aws iamdb.zip is unreachable

### ISSUE THREAD

**Issue by GellertPalfi** [the-full-stack/fsdl-text-recognizer-2022#81]
lab04_experiments.ipynb has this field:
```
%%time
import torch


gpus = int(torch.cuda.is_available()) 

%run training/run_experiment.py --model_class LineCNNTransformer --data_class IAMLines \
  --loss transformer --batch_size 32 --gpus {gpus} --max_epochs 2 \
  --limit_train_batches 0.1 --limit_val_batches 0.1 --limit_test_batches 0.1 --log_every_n_steps 10
```
  however running the field throws an `HTTPError: HTTP Error 403: Forbidden` error.
  Trying to reach the website by the browser also throws an error: `AllAccessDisabledAll access to this object has been disabled9KC8W9JEZG5F4YVEUtjDQygwlZMxnZkbzEZZ3DA+oejfVlwfCZBuXXaS8a6LRSxnYfpctNNwyRmjxx3qd+z6+LkVl60=`
Probably more files are affected by this issue

**Comment by charlesfrye** [comment]
thanks for the report! will look into it

**Comment by GellertPalfi** [comment]
sorry forgot to include the link: https://s3-us-west-2.amazonaws.com/fsdl-public-assets/iam/iamdb.zip

**Comment by GellertPalfi** [comment]
in the meanwhile could you provide the zip files or future files? @charlesfrye so I could continue with the course

**Comment by charlesfrye** [comment]
We're having some trouble with our Amazon account, so we actually can't access the files either! Will let you know once it's resolved.

**Comment by charlesfrye** [comment]
this is fixed, as of a few days ago. appreciate your patience!
